### ISSUE TITLE
Add FB login callbacks 

### ISSUE THREAD

**Issue by alex2binny** [alex2binny/shadchanapp_web#8]
* When coming to the homepage there is a check for 'if logged in already'. need to decide what to do.
* Also when user hits the login button, need to create callbacks for that.

**Comment by EzraShimon** [comment]
Doesn't the user just bypass the login page and go directly to the suggestions page if she is already logged in?

**Comment by EzraShimon** [comment]
I spoke about this with Binny in person, and the answer to my question was, "yes."
